### ISSUE TITLE
is there a prebuilt docker image and docker compose example?

### ISSUE THREAD

**Issue by aniel300** [OpenMaxIO/openmaxio-object-browser#8]
is there a prebuilt docker image and docker compose example? and docs? i should i used the docs from minio

**Comment by jnfinitym** [comment]
They are WIP and should be up by the end next week, that's the aim anyways.

**Comment by jamesagarside** [comment]
Ive built a Dockerfile for the time being so I can use this UI, found here https://github.com/jamesagarside/openmaxio-object-browser/blob/openMaxIO-main/Dockerfile

**Comment by xwndo** [comment]
Hope to have a Docker version as soon as possible

**Comment by aniel300** [comment]
@jnfinitym thank you 🙏

**Comment by mrkhachaturov** [comment]
I have a repository where I'm building containers for personal use: [Astrateam Containers Repository](https://github.com/astrateam-net/containers).

Thanks to @jamesagarside, I've incorporated his Dockerfile into the project. You can either use the pre-built container `ghcr.io/astrateam-net/minio-browser:1.7.6` or create your own custom container.

Docker compose example: 

```yaml 
  minio-local-browser:
    image: ghcr.io/astrateam-net/minio-browser:1.7.6
    container_name: minio-local-browser
    restart: unless-stopped
    command: ./console server
    environment:
      # Replace with the URL of your MinIO server
      CONSOLE_MINIO_SERVER: http://192.168.20.10:9000
```
